#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @import shiny
#' @importFrom bslib bs_theme
#' @importFrom dplyr across
#' @importFrom dplyr arrange
#' @importFrom dplyr bind_rows
#' @importFrom dplyr count
#' @importFrom dplyr desc
#' @importFrom dplyr filter
#' @importFrom dplyr full_join
#' @importFrom dplyr group_by
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr n
#' @importFrom dplyr pull
#' @importFrom dplyr rename
#' @importFrom dplyr select
#' @importFrom dplyr summarise
#' @importFrom dplyr ungroup
#' @importFrom htmlwidgets JS
#' @importFrom httr2 req_body_form
#' @importFrom httr2 req_perform
#' @importFrom httr2 request
#' @importFrom httr2 resp_body_string
#' @importFrom magrittr %>%
#' @importFrom purrr flatten_chr
#' @importFrom purrr map
#' @importFrom purrr map_depth
#' @importFrom purrr pluck
#' @importFrom quanteda corpus
#' @importFrom quanteda dfm
#' @importFrom quanteda docnames
#' @importFrom quanteda kwic
#' @importFrom quanteda phrase
#' @importFrom quanteda tokens
#' @importFrom quanteda.textstats textstat_frequency
#' @importFrom rclipboard rclipboardSetup
#' @importFrom rclipboard rclipButton
#' @importFrom reactable colDef
#' @importFrom reactable colFormat
#' @importFrom reactable getReactableState
#' @importFrom reactable reactable
#' @importFrom reactable reactableOutput
#' @importFrom reactable renderReactable
#' @importFrom revtools [.bibliography
#' @importFrom rlang .data
#' @importFrom rlang .env
#' @importFrom rlang set_names
#' @importFrom shiny fluidPage
#' @importFrom shinyFeedback useShinyFeedback
#' @importFrom stats frequency
#' @importFrom stats var
#' @importFrom stats xtabs
#' @importFrom stringr str_replace_all
#' @importFrom stringr str_split
#' @importFrom stringr str_split_1
#' @importFrom tibble add_column
#' @importFrom tidyr pivot_wider
#' @importFrom tidyr replace_na
#' @importFrom tidyselect any_of
#' @importFrom tidyselect where
#' @importFrom tools file_path_sans_ext
#' @importFrom utils head
#' @importFrom utils read.csv2
#' @importFrom utils read.table
#' @importFrom utils tail
#' @importFrom utils write.csv2
#' @importFrom withr with_seed
## usethis namespace: end
NULL
